[package]
name = "busy-metrics"
version.workspace = true
edition.workspace = true

[dependencies]
busy-core.workspace = true
windows = { workspace = true, features = [
    "Wdk_System_SystemInformation",
    "Win32_Foundation",
    "Win32_System_Performance",
    "Win32_System_Power",
    "Win32_System_ProcessStatus",
    "Win32_System_Registry",
    "Win32_System_SystemInformation",
    "Win32_System_Threading",
    "Win32_System_WindowsProgramming",
] }

[lints]
workspace = true
