[package]
name = "busy-sensors"
version.workspace = true
edition.workspace = true

[dependencies]
busy-core.workspace = true
windows = { workspace = true, features = [
    "Wdk_Graphics_Direct3D",
    "Wdk_System_SystemInformation",
    "Win32_Foundation",
    "Win32_Graphics_Dxgi",
    "Win32_System_Performance",
    "Win32_System_Threading",
] }

[lints]
workspace = true
