[package]
name = "busy-win"
version.workspace = true
edition.workspace = true

[dependencies]
windows = { workspace = true, features = [
    "Win32_Foundation",
    "Win32_Globalization",
    "Win32_System_LibraryLoader",
    "Win32_System_Performance",
    "Win32_System_Registry",
] }

[lints]
workspace = true
